export const FETCH_HOMES = 'FETCH_HOMES'

export const FETCH_USER_HOMES = 'FETCH_USER_HOMES'

export const SET_CURRENT_HOME = 'SET_CURRENT_HOME'

export const FETCH_LATEST_HOMES = 'FETCH_LATEST_HOMES'

export const FETCH_AVAILABILITY = 'FETCH_AVAILABILITY'

export const FETCH_USERS = 'FETCH_USERS'
export const SET_CURRENT_USER = 'SET_CURRENT_USER'

export const FETCH_PAST_GUEST_TRANSACTIONS = 'FETCH_PAST_GUEST_TRANSACTIONS'

export const FETCH_FUTURE_GUEST_TRANSACTIONS = 'FETCH_FUTURE_GUEST_TRANSACTIONS'

export const FETCH_HOST_TRANSACTIONS = 'FETCH_HOST_TRANSACTIONS'

export const FETCH_USER_CART = 'FETCH_USER_CART'

export const CREATE_USER_CART = 'CREATE_USER_CART'

export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM'

export const DISPLAY_UPCOMING = 'DISPLAY_UPCOMING'

export const DISPLAY_PAST = 'DISPLAY_PAST'

export const DISPLAY_HOST_HISTORY = 'DISPLAY_HOST_HISTORY'
