export const FETCH_HOMES = 'FETCH_HOMES'

export const SET_CURRENT_HOME = 'SET_CURRENT_HOME'

export const FETCH_AVAILABILITY = 'FETCH_AVAILABILITY'

export const FETCH_USERS = 'FETCH_USERS'

export const SET_CURRENT_USER = 'SET_CURRENT_USER'

export const FETCH_GUEST_TRANSACTIONS = 'FETCH_GUEST_TRANSACTIONS'

export const FETCH_HOST_TRANSACTIONS = 'FETCH_HOST_TRANSACTIONS'
