export const FETCH_HOMES = 'FETCH_HOMES'

export const FETCH_LATEST_HOMES = 'FETCH_LATEST_HOMES'

export const SET_CURRENT_HOME = 'SET_CURRENT_HOME'

export const FETCH_AVAILABILITY = 'FETCH_AVAILABILITY'

export const FETCH_USERS = 'FETCH_USERS'

export const SET_CURRENT_USER = 'SET_CURRENT_USER'

